/**
 * Shared e2e selector registry — data-testid only.
 * Specs MUST import from here; never inline testid strings.
 */
export const sel = {
  // Shell / nav
  appShell: "app-shell",
  appContent: "app-content",
  appSidebar: "app-sidebar",
  sidebarBrand: "sidebar-brand",
  unauthenticated: "unauthenticated",
  unauthRelaunch: "unauth-relaunch",
  bannerStack: "banner-stack",
  bannerConnection: "banner-connection",
  bannerReducedFidelity: "banner-reduced-fidelity",
  bannerObserveMode: "banner-observe-mode",
  bannerResync: "banner-resync",
  routeSuspense: "route-suspense",

  sidebarItem: (id: string) => `sidebar-item-${id}`,

  // Surfaces
  surfaceMission: "surface-mission",
  surfaceReplay: "surface-replay",
  surfaceHealth: "surface-health",
  surfaceLeaderboard: "surface-leaderboard",
  surfacePlans: "surface-plans",
  surfaceFeatures: "surface-features",
  surfaceAudits: "surface-audits",
  surfaceMemory: "surface-memory",
  surfaceSpecs: "surface-specs",
  surfaceTokens: "surface-tokens",
  surfaceConfig: "surface-config",

  // Mission
  missionBoard: "mission-board",
  missionRoster: "mission-board-roster",
  missionBoardRow: (id: string) => `mission-board-row-${id}`,
  missionBoardChip: (id: string) => `mission-board-chip-${id}`,
  missionBoardRoster: (id: string) => `mission-board-roster-${id}`,
  missionViewRoster: "mission-board-view-roster",
  missionViewGraph: "mission-board-view-graph",
  missionGraphHost: "mission-board-graph-host",
  missionEventStream: "mission-event-stream",
  missionEventList: "mission-event-stream-list",
  missionEventEmpty: "mission-event-stream-empty",
  missionStreamItem: (id: string) => `mission-event-stream-item-${id}`,
  missionChainline: "mission-chainline",
  missionZero: "mission-zero",
  missionEmpty: "mission-empty",
  missionInspector: "mission-inspector",
  missionInspectorLive: "mission-inspector-live",

  // Replay
  replayScrub: "replay-scrub",
  replayScrubChainline: "replay-scrub-chainline",
  replayScrubLine: "replay-scrub-line",
  replayScrubber: "replay-scrub-line-scrubber",
  replayPlayhead: "replay-scrub-line-scrubber-playhead",
  replayRail: "replay-scrub-line-scrubber-rail",
  replayBoard: "replay-board",
  replayBoardStage: "replay-board-stage",
  replayBoardStream: "replay-board-stream",
  replayBoardCurrent: "replay-board-current-label",
  replayHistory: "replay-history",
  replayHistoryRow: (id: string) => `replay-history-row-${id}`,
  replayDegraded: "replay-scrub-degraded",
  replaySingle: "replay-scrub-single",

  // Memory
  memoryRail: "memory-rail",
  memoryRailCreate: "memory-rail-create",
  memoryRailList: "memory-rail-list",
  memoryViewList: "memory-view-list",
  memoryViewGraph: "memory-view-graph",
  memoryEmpty: "memory-empty",
  memoryConflict: "memory-conflict",
  entryEditor: "entry-editor",
  entryEditorCategory: "entry-editor-category",
  entryEditorContent: "entry-editor-content",
  entryEditorSave: "entry-editor-save",
  entryEditorCancel: "entry-editor-cancel",
  entryEditorPending: "entry-editor-pending",
  entryEditorConfirmed: "entry-editor-confirmed",
  entryView: "entry-view",
  entryViewEdit: "entry-view-edit",
  entryViewDelete: "entry-view-delete",
  entryViewTitle: "entry-view-title",
  inlineConfirm: "inline-confirm",
  inlineConfirmConfirm: "inline-confirm-confirm",
  inlineConfirmCancel: "inline-confirm-cancel",
  memoryGraph: "memory-graph",

  // Config / management
  mgmtRail: "mgmt-rail",
  mgmtRailRow: (id: string) => `mgmt-rail-row-${id}`,
  configEditor: "config-editor",
  configEditorSave: "config-editor-save",
  configEditorDirty: "config-editor-dirty",
  configEditorSaved: "config-editor-saved",
  configEditorError: "config-editor-error",
  configEditorRawToggle: "config-editor-raw-toggle",
  configForm: "config-form",
  configField: (id: string) => `config-field-${id}`,
  configFieldInput: (id: string) => `config-field-${id}-input`,
  configUnrecognized: "unrecognized-keys",
  configUnrecognizedJson: "unrecognized-keys-json",
  rawJsonEditor: "raw-json-editor",
  rawJsonTextarea: "raw-json-editor-textarea",
  handoffPanel: "handoff-panel",
  handoffList: "handoff-list",
  handoffItem: (slug: string) => `handoff-item-${slug}`,
  handoffStatus: (slug: string) => `handoff-status-${slug}`,
  handoffSlug: (slug: string) => `handoff-slug-${slug}`,
  handoffTransition: (slug: string) => `handoff-transition-${slug}`,
  handoffTransitionBtn: (slug: string) => `handoff-transition-btn-${slug}`,
  handoffTransitionError: (slug: string) => `handoff-transition-error-${slug}`,
  markerPanel: "marker-panel",
  restorePanel: "restore-panel",

  // Plans / features / audits / health
  plansSplit: "plans-split",
  plansEmpty: "plans-empty",
  featuresSurface: "surface-features",
  auditsHeatmap: "audits-heatmap",
  auditsHeatmapPopover: "audits-heatmap-popover",
  healthZero: "health-zero",
  leaderboardEmpty: "leaderboard-empty",
  tokensZero: "tokens-zero",
  graphToolbarViewToggle: (base: string) => `${base}-view-toggle`,
} as const;

/** Playwright locator helper for a registry testid. */
export function tid(id: string): string {
  return `[data-testid="${id}"]`;
}
